---
title: 文献笔记-抑郁症大脑功能网络拓扑属性的改变
author: 桑峰
date: 2021-04-16
slug: blog
output: html_document
categories:
  - 文献笔记
tags:
  - fmri
  - 功能网络
  - 图论分析
  - 抑郁症
  - 小世界属性
---

### Title

> Disrupted Brain Connectivity Networks in Drug-Naive, First-Episode Major Depressive Disorder

### Results

1. MDD患者表现出了全局属性的改变：更短的最短路径长度和更高的全局效率→朝着随机网络转变；
2. 尾状核和默认网络脑区中心性在MDD组中增加；
3. 枕叶、眶额和颞叶脑区中心性下降；

### Conclustions

1. MDD is associated with disruptions in the topological organization of functional brain networks;
2. Disruption in the topological organization may contribute to disturbances in mood and cognition in MDD;

### Notes

1. 网络稀疏性选择标准：(1) 网络平局度>2*log(N)，N为网络节点数；(2) 小世界属性大于1.1；
2. AUC指标提供了独立与单个稀疏性下的综合度量，summaried scale;
3. NBS, Network-based statistic, 对网络中的连边进行统计的方法；
4. Nonparametric permutation test;
5. Combination of high local clustering and short path length supports the two fundamental organizational principles in the brain: functional segregation and functional integration;

### Links

1. https://doi.org/10.1016/j.biopsych.2011.05.018