---
title: 文献笔记-大脑功能网络的分离与整合
author: 桑峰
date: 2021-05-05
slug: blog
output: html_document
categories:
  - 文献
tags:
  - fMRI
  - segregation
---

### Title

> Segregated systems of human brain networks

### Notes

RSFC **within and between brain system** exhibits progressive difference across adulthood, even in the absence of disease.

Increasing age is associated with decreasing connectivity within systems and increasing connectivity between brain systems.

- increasing age is accompanied by decreasing segregation
- different types of functional systems exhibit different trajectories of age-related differences in system segregation

With healthy adult , increasing segregation is associated with superior cognitive ability independently of influence of age.

Higher RSFC segregation exhibit the greatest improvements, and positivity correlate with improvement in the therapy.

**$Segregation=(within-between)/within$**

**Modularity** is calculated as the fraction of edges that fall within the given communities of a network compared to the expected fraction if the connections were distributed at random across the network.

### Future

System segregation of an **individual change over time** and relation to their health

How do properties of the **anatomical network** of brain relate to the maintenance and  modulation in segregation and integration of the brain network's functional systems?

Mechanisms of **dynamically** adjust the segregation and integration

**Optimal network regime or configuration**, in aging and disease the differences in segregation 

**Individual differences**

### Reference

Wig, G. S. . (2017). Segregated systems of human brain networks. Trends in Cognitive Sciences, 21(12), 981-996.