---
title: 一周小结
author: 桑峰
date: 2021-08-30
slug: blog
output: html_document
categories:
  - Toolbox
tags:
  - GRETNA
  - CAT12
---

本文记录了上周笔者在使用GRETNA和CAT12中遇到的一些问题和想法。

# GRETNA

GRETNA是脑网络中进行图论分析的一款工具包。它也支持对于静息态功能磁共振成像(fMRI)数据的预处理。在fMRI数据的网络拓扑分析中，最常见的网络建模方式是功能连接网络。其中，网络的节点表示脑区，而网络连边表示不同脑区BOLD信号时间序列的相关值——相关值越高，表明两个脑区连接越紧密。

网络中连边值的问题是重要的，因为在另外一些网络中，网络连边值越高表明两个节点之间的代价越高。例如在公路网络中，节点为不同的城市，连边表示不同城市之间的距离。

在GRETNA计算网络的平均距离时，在得到距离矩阵后进行了取倒数的操作。这一步，对于相关系数网络，即连边值越到，节点连接越紧密的加权网络而言是合适的。因为距离矩阵中的值表示的含义是两个节点之间的最短路径的权重和。它的值越大，表明两个节点连接越紧密。为了与通常的距离越远，代价越高的认知相一致，取倒数后就保证了连接越紧密的节点，它们的“距离”也越短。

但对于二值网络而言，两个节点的距离是其最短路径中边的条数，也就是距离矩阵中的值的含义。节点距离越近，它们的连边条数也越少，“距离”也越短。因此这里不应该在进行取倒数的操作。

# CAT12

使用CAT12中的Segment模块进行皮层构建时，默认会得到个体皮层厚度的文件。如果要进行SBM分析，还需要将个体皮层厚度文件转换到标准空间(fsaverage)中，这一步在CAT12中是包含在resample模块中的。

另外，CAT12也提供了提取ROI上相关指标的功能。它在提取ROI指标时，也是将个体的指标文件转换到标准空间中，再计算图谱文件(annotation)定义的ROI的指标。这里个体指标转换到标准空间使用的也是resample模块，不过这里的平滑核是0. 这也是容易理解的，因为在计算ROI指标时，会平均整个ROI中所有的Vertex。这样由于个体指标再转换到标准空间中产生的误差就会被平均掉。而在进行SBM分析时，因为是逐Vertex进行的统计，上面的误差就会对统计产生影响，因此在SBM中，resample并且设置合适的平滑核大小是重要的。
