---
title: 文献笔记-大脑功能网络中体现的左右半球和性别差异
author: 桑峰
date: 2021-04-18
slug: blog
output: html_document
categories:
  - 文献笔记
tags:
  - rest-fMRI
  - sex differences
  - hemsiphere differences
---

### Title

> Hemisphere- and gender-related differences in small-world brain networks: A resting-state functional MRI study

### Results

Male have a large normalized clustering coefficient in the right hemispheric network, but a lower clustering coefficient in the left hemispheric network.

Significant hemisphere-related differences in the regional nodal characteristics: frontal and occipital regions (leftward asymmetry), temporal regions (rightward asymmetry).

### Conclustions

Topological organization of human brain functional networks is associated with gender and hemispheres.

### Notes

Alterations of brain asymmetries are associated with behavior changes in normal aging and in various neuropsychiatric and neurological diseases such as schizophrenia, stroke and dyslexia.

Statistically, males perform better in right-lateralized visuospatial perception processing, whereas females have advantages in left-lateralized language processing.

Small-world properties is used to identify the range of sparsity (10%~46%). ($\gamma>1$, $\lambda\approx1$, and $\sigma>1.2$)

Generate the comprehensive score by multiplying the sparsity interval and measures at all sparsities.

Hub node is at least one standard deviation greater than the average of parameter (x > mean + SD).

Asymmetry score (A) = 100 * (R-L)/(0.5*(R+L)), and positive asymmetry scores indicated right-ward asymmetry and vice versa.

### Links

1. https://doi.org/10.1016/j.neuroimage.2010.07.066